### ISSUE TITLE
X-Forwarded-For 头部

### ISSUE THREAD

**Issue by nutinshell** [xjdrew/gotunnel#11]
能否增加 X-Forwarded-For 头部传递给后端 squid 的选项，以便记录。

**Comment by xjdrew** [comment]
gotunnel目前致力于做透明tcp tunnel，没考虑修改应用数据包

**Comment by nutinshell** [comment]
但是有啥办法区分不同的接入用户呢，无法把用户的真实IP传递给squid，感觉不太完美。。

**Comment by xjdrew** [comment]
目前确实没有办法区分不同用户；
跟squid配合只是gotunnel的一种应用场景，所以没必要为squid加特殊的东西。
如果你需要对squid有特殊支持，可以fork这个项目，然后按照自己的需求改一下。
如果修改后不破坏对其他协议的支持，可以pr给我。

**Comment by nutinshell** [comment]
这并不是对 squid 的特殊支持，X-Forwarded-For 头部传递到后端基本都是这类程序的基本功能，当然更好的是支持 proxy protocol。

**Comment by xjdrew** [comment]
X-Forwarded-For 是http协议里面的东西，gotunnel跟http协议没有关系。比如现在我把gotunnel用于做mysql的隧道。

**Comment by nutinshell** [comment]
酱紫的。那支持 [proxy protocol v1](https://github.com/armon/go-proxyproto) 应该是最好的选择 ：)

**Comment by xjdrew** [comment]
谢谢提供信息，看上去支持这个协议是个不错的选择；
不过支持这个协议之后，后端就不能透明使用了。比如squid，还是不知道客户端ip。必须改造squid这类软件，使其能够读取包头的proxy信息。

**Comment by nutinshell** [comment]
[Proxy protocol](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt) 现在基本是个通用标准，squid3 stunnel 之类的都已经支持 ：D
