### ISSUE TITLE
怎么翻不了墙呢？

### ISSUE THREAD

**Issue by luckypoem** [xjdrew/gotunnel#13]
hi。
我服务器端和客户端都设置好了，怎么翻不了墙呢？

客户端的运行情况：
yudeMacBook-Air:~ yuming$ ps aux|grep go tunnel
yuming            520   0.0  0.1 573395136   6180   ??  S     1:41下午   0:00.19 /Users/yuming/gotunnel/bin/gotunnel -listen=127.0.0.1:7070 -backend=23.xx.yy.zz:8001 -secret=ilovepeide -tunnels=100
yuming            577   0.0  0.0  2441988    656 s000  S+    2:17下午   0:00.01 grep gotunnel
yudeMacBook-Air:~ yuming$ 

服务器端的运行情况：
root@VM:~# ps aux|grep go tunnel
root      1784  0.0  6.2 199376 16372 ?        Sl   Oct24   0:01 ./gotunnel -listen=:8001 -backend=127.0.0.1:3128 -secret=ilovepeide -tunnels=0
root     11244  0.0  0.3   8812   844 pts/3    S+   02:20   0:00 grep --color=auto gotunnel
root@VM:~#
root@VM:~/go/bin# netstat -anp|grep 3128
tcp6       0      0 :::3128                 :::*                    LISTEN      1140/squid3     
root@VM:~/go/bin#

设置firefox的socks5代理为127.0.0.1:7070，但是就是翻不了墙，为什么呢？

**Comment by xjdrew** [comment]
自己检查一下配置：
1. 先检查服务器上代理是不是配置对了
2. 再看gotunnel的连接建立好了没

另外：3128端口，看上去是squid的默认端口，为什么客户端设置socks5代理呢？

**Comment by luckypoem** [comment]
hi.
哦，原来本地代理要设为http代理啊。我把本地代理设为http代理（127.0.0.1:7070）后，确实可以翻墙了。但速度好慢啊，打开一个被封的网页要3分钟左右。而使用建立在同一台服务器上的ss,几乎是秒开被封的网页。有什么办法改进一下速度吗？

**Comment by luckypoem** [comment]
hi.
我把服务器端的backend程序改为了某个socks代理服务器程序，这样翻墙就秒开了。先头用squid做后端，导致翻墙慢，原因可能是squid太臃肿，导致效率低下

**Comment by xjdrew** [comment]
squid3不应该这么慢吧，是不是有些配置不合适？

**Comment by luckypoem** [comment]
hi.
我没有修改squid3的配置文件，所以有些配置不合适吗？你修改了squid3的配置文件的什么地方呢？
