### ISSUE TITLE
undefined: sync.Pool

### ISSUE THREAD

**Issue by OhCoder** [xjdrew/gotunnel#14]
环境ubuntu 13.03
go version go1.2.1 linux/amd64

<img width="729" alt="screen shot 2015-12-27 at 1 57 29 am" src="https://cloud.githubusercontent.com/assets/890676/12007393/9422e600-ac3d-11e5-8e8a-adbaaad5db1b.png">

安装出现问题。

**Comment by xjdrew** [comment]
sync.Pool是1.4增加的，好像
