### ISSUE TITLE
Would you please support blowfish encrypt/decrypt?

### ISSUE THREAD

**Issue by netroby** [xjdrew/gotunnel#3]
Would you please support blowfish encrypt/decrypt?
https://godoc.org/golang.org/x/crypto/blowfish

**Comment by xjdrew** [comment]
加了认证和加密：
https://github.com/xjdrew/gotunnel/commit/b988069c3c78da97c94121c0f94dcd155dcfd5ec

原理：
双方基于事先约定的密钥，互相认证；
认证失败，服务器主动关闭连接；
认证成功后通过认证过程中的双方都知道的随机数，生成密钥，用于后面的数据传输加密。

数据加密使用加密强度稍微弱一点但是速度非常快的流加密算法rc4，我觉得rc4够用了。blowfish是块加密算法，加密流数据稍显麻烦。决定不用。

**Comment by netroby** [comment]
Thanks.

**Comment by vzex** [comment]
原来，是gotunnel，我特么以为是dogtunnel的issue

**Comment by netroby** [comment]
WTF? @vzex  I am very strange, why you appear here.
