### ISSUE TITLE
连接出现错误？

### ISSUE THREAD

**Issue by cfcboy** [xjdrew/gotunnel#7]
服务端（centos x64）：gotunnel -tunnels=0 -listen=:443 -backend=127.0.0.1:8888 secret="123" -log=10
客户端（centos x64或win7 x64）：gotunnel -tunnels=100 -listen="127.0.0.1:8080" -backend="*.*.*.*:443" -secret="123" -log=10
统一错误：
read token failed(*.*.*.*:12362):read tcp *.*.*.*:12362: connection reset by peer
read token failed(serverip:55374):EOF
能帮忙看一下吗？

**Comment by cfcboy** [comment]
测试8888正常，防火墙已经开启。

**Comment by xjdrew** [comment]
是不是服务器的443端口没有打开呢？

cfcboy <notifications@github.com>于2015年7月9日周四 上午1:10写道：

**Comment by cfcboy** [comment]
防火墙已经开启。
