### ISSUE TITLE
Can not create tunnel

### ISSUE THREAD

**Issue by netroby** [xjdrew/gotunnel#9]
15/08/27 21:16:26.551670 create tunnel: 192.168.11.9:45061 <-> 45.**.**.**5:8001
2015/08/27 21:16:26.606621 challenge(45.**.**.**5:8001), len 32, [121 212 42 211 5 203 39 198 30 25 134 235 255 173 191 58 54 199 198 4 177 84 190 129 148 94 113 84 151 255 222 13]
2015/08/27 21:16:26.606749 exchange challenge failed(45.**.**.**5:8001)

**Comment by xjdrew** [comment]
does client's secret match server's?

**Comment by netroby** [comment]
Yes, it matched.

**Comment by xjdrew** [comment]
please update gotunnel source code, and try again. If failed again, please paste launch parameters :-)
